- app/jobs/govbox/download_message_job.rb
- app/jobs/govbox/process_message_job.rb
Chceme vyriešiť problém, kedy sa súbežne môžu naplánovať 2 rovnaké Govbox::DownloadMessageJobs, vtedy chceme:
- aby sa UPVS správa nevytvorila duplicitne
- aby sa UPVS správa nesprocessovala duplicitne.
> GO-2 Update Govbox::DownloadMessageJob

- app/components/signing/signers_requests/component.html.erb
Pri vybere podpisujucich je nespravny nadpis "Dokumenty na podpis".
Je to matuce hlavne ak sprava ma iba formular (1 objekt), vtedy sa automaticky zvoli iba formular na podpis a pouzivatel sa zobrazi az tato obrazovka:
> GO-12 Fix heading in Signing::SignersRequests::Component

- app/controllers/message_drafts/document_selections_controller.rb
- app/models/message_template.rb
Pridava handlovanie stavu, kedy sprava este nie je vyplnena, ale pouzivatel by uz chcel podpisovat. Primergovat chceme do sablonovej vetvy, lebo tam to uz je predpripravene.
https://github.com/slovensko-digital/govbox-pro/assets/43437253/f6426729-7de7-41fa-a547-22021a229c4c
> GO-20 Fix signing empty form

- config/application.rb
Checkovanie mapovania sprav bolo nespravne pridane, co sposobilo prepisanie configu pre sync. 
Navrhujem pridat nejaky check, kedy naposledy zbehol sync schranok, aby sme boli upozorneni na taketo veci.
> Fix GoodJob cron config

- app/jobs/govbox/submit_message_draft_job.rb
Ak su `message_draft.template&.metadata` nil (ked nebola pouzita sablona), tak dostaneme error.
> Fix MessageDrafts without template submission

- app/jobs/govbox/authorize_delivery_notification_job.rb
Riesi problem iba ciastocne. Neoznaci aspon uz prevzatu notifikaciu o doruceni za neprevzatu (po vyfailovani jobu), ale stale neriesi problem prevzatia mimo GO a nasledne prebratie v GO medzi zbehnutim syncu. Aby sme vedeli poriesit aj tento problem, ziadala by sa uprava na strane GB API (aby v response bola sprava o tom, ze sa nepodarilo prevziat kvoli tomu, ze uz je pravzata). Aktualne GB API vracia 500, 'Unknown error'.
> GO-63 Do not authorize delivery notification if already marked authorized

- app/controllers/api_controller.rb
Toto som našiel, keď som tento kúsok kódu chcel použiť inde, tak som rovno fixol. V `render_bad_request` sa volá `error.message`, čo na symbole padalo a vracalo 500.
> Pass error object to render_bad_request instead of symbol

- app/models/message.rb
Toto sme chceli upratat, tym, ze dame templatu default `{}`. Nezafunguje to vsak v pripade, ak draft nie je vytvoreny z templatu (teda `template` je `nil`).
> Fix MessageDraft.all_metadata method

- app/controllers/api/messages_controller.rb
- app/models/signature_requested_from_tag.rb
- app/models/signed_by_tag.rb
- app/models/tenant.rb
- test/integration/upvs_message_drafts_api_test.rb
Chceme povlit pridanie iba  `SignareureRequestedFromTag`s a `SignedByTag`s k MessageObjectom.
> GO-66 Update assigning tags to objects in MessagesAPI

- app/jobs/drafts/load_content_job.rb
- app/lib/event_bus.rb
- app/models/message.rb
- app/models/message_draft.rb
- test/lib/event_bus_test.rb
Zistila som, ze v importovanych draftoch nie je mozne vyhladavat na zaklade ich obsahu, kedze sa atributy spravy updatuju postupne, ako sa draft spracovava a `EventBus` neodobera event `:message_changed`. Takze ked [neskor v postupe spracovania](https://github.com/slovensko-digital/govbox-pro/blob/GO-66/subscribe_for_message_changed_event/app/jobs/drafts/load_content_job.rb#L22) nastavime sprave html vizualizaciu, tak nezbehne reindex.
Navrhla som upravu, aby `EventBus` tento event odoberal.
> GO-66 Subscribe for :message_changed event

- app/components/message_draft_body_component.html.erb
- app/jobs/drafts/load_content_job.rb
- app/lib/event_bus.rb
- app/models/message.rb
- app/models/message_object_datum.rb
- db/migrate/20240501213603_update_messages_html_visualization.rb
- db/schema.rb
- test/fixtures/messages.yml
- test/fixtures/upvs/form_related_documents.yml
- test/models/message_test.rb
Po nacitani obsahu formulara potrebujeme pri draftoch ulozit HTML vizualizaciu. Pri importovanych draftoch sme to doteraz priamo vynucovali po nacitani vsetkych message objektov, ale pri API mi to pride ako tahanie logiky do controllera, kedze by sme to potrebovali dat niekde sem: https://github.com/slovensko-digital/govbox-pro/blob/main/app/controllers/api/messages_controller.rb#L34, tak som to vytiahla do `EventBus`.
Doteraz sme to pri draftoch z API neriesili a teda ich obsah nie je indexovany, kedze `html_visualization` je `nil`.
Bolo by fajn spravit aj nejaky update existujucich draftov.
> GO-66 Automatically set Message.html_visualization after form data create

- app/policies/message_draft_policy.rb
- app/policies/upvs/message_draft_policy.rb
Aktualne sa tlacidlo exportu zobrazuje aj pri draftoch, ale chyba policy, takze export zlyha. Sice export pri draftoch neviem ci je potrebny, ale nevidim ani dovod ho zakazovat.
> GO-92 Allow export on message drafts

- app/models/fs/api_connection.rb
- test/fixtures/api_connections.yml
- test/fixtures/boxes.yml
- test/models/fs/api_connection_test.rb
Problem doteraz bol taky, ze ak sa mali nacitat z FS dva boxy, ktore mali rovnake inicialy, tak bola validacia na `short_name` neuspesna a vytvoril sa iba jeden box s danymi inicialmi.
Natrafili sme na to pri testovani s potenc. klientom.
> GO-110 Fix generating FS boxes short name

- app/models/box.rb
- app/models/fs/api_connection.rb
- app/models/fs/box.rb
- app/models/fs/message_draft.rb
- app/models/upvs/box.rb
- db/migrate/20240716140732_update_fs_boxes_settings.rb
- db/migrate/20240716140732_update_fs_boxes_settings_and_uri.rb
- db/schema.rb
- test/fixtures/boxes.yml
- test/models/fs/api_connection_test.rb
Schranky, ktore su z oblasti SPD zatial oznacujeme, ze nie su urcene na podania, aby sme dosiahli to, ze vo zvysnych schrankach, tych, ktore su urcene na podania bude unikatne DIC.
Aktualne to nema ziaden dosah, nakolko SPD formulare ani FS API zatial rozparsovat nevie, takze take podania zatial odmietame.
> GO-110 Add message_drafts_import_enabled attribute to box settings

- app/jobs/govbox/process_message_job.rb
- db/migrate/20240814102352_add_unique_index_on_uuid_message_thread_id_to_messages.rb
- db/schema.rb
- test/models/message_draft_test.rb
Ukazalo sa, ze niektore spravy v core domene mame duplicitne. Predpokladam, ze prislo k subeznemu spusteniu dvoch `Govbox::ProcessMessageJob`ov nad rovnakou spravou.
Pozerala som opatrne individualne pripady a precistila to radsej manualne. Bolo by vhodne podla mna pridat unique index na uuid v ramci threadu.
> Add unique index on uuid, message_thread_id to Messages

- app/components/message_threads_table_row_component.html.erb
- app/helpers/message_thread_helper.rb
- app/models/box.rb
- app/models/fs/box.rb
- app/models/upvs/box.rb
- test/system/fs/message_drafts_test.rb
Pri UPVS boxoch je mozna komunikacia ku viacerym subjektom, tak v pripade outboxovych sprav chceme na threade zobrazovat komu posledna outboxova sprava isla, inak odosielatela.
Pri FS boxoch je mozna komunikacia iba k jednemu subjektu (FS), tak chceme na threade zobrazovat vzdy odosielatela.
> GO-127 Show sender name by FS MessageThreads

- app/controllers/api/messages_controller.rb
- app/controllers/message_drafts_controller.rb
- app/controllers/message_threads/bulk/message_drafts_controller.rb
- app/jobs/upvs/drafts/load_content_job.rb
- app/models/fs/message_draft.rb
- app/models/message.rb
- app/models/message_draft.rb
- app/models/message_object.rb
- app/models/message_thread.rb
- app/models/tag.rb
- db/migrate/20241029064753_remove_to_be_signed_attribute_from_message_objects.rb
- db/schema.rb
- public/openapi.yaml
- test/fixtures/message_object_data.yml
- test/fixtures/message_objects.yml
- test/fixtures/messages.yml
- test/integration/upvs_message_drafts_api_test.rb
- test/models/message_object_test.rb
- test/system/message_drafts_test.rb
Nahradza: https://github.com/slovensko-digital/govbox-pro/pull/454
> GO-49 Do not submit message unless requested signatures present

- app/models/message_object_datum.rb
Potrebujeme zmenit callback, aby sa nevytvorili `NestedMessageObjects` az pri commite, potrebujeme s nimi pracovat ihned po vytvoreni `MessageObjects`, pri vytvarani vizualizacie.  https://github.com/slovensko-digital/govbox-pro/blob/main/app/models/fs/message.rb#L44-L45
> GO-128 Update callback to create nested message objects

- app/jobs/fs/validate_message_draft_result_job.rb
Kedze nemame zanalyzovane, co vsetko sa v diffe moze vyskytovat a ako presne to chceme pouzivatelovi komunikovat, tak zatial by sme si to iba logovali a pouzivatelovi nic o diffe nehovorili.
> GO-141 Do not inform user about message_draft diff in validations

- app/jobs/fs/download_sent_message_job.rb
- app/jobs/fs/sync_box_job.rb
- app/jobs/govbox/process_message_job.rb
- app/models/message.rb
Pri syncovani boxu chceme stahovat iba suvisiace spravy k plnohodnotnym outboxovym spravam, aby sme vylucili drafty.
> GO-128 Do not download related messages to drafts

- app/models/box.rb
- app/models/fs/box.rb
- app/models/fs/message_draft.rb
- test/fixtures/api_connections.yml
- test/fixtures/boxes.yml
- test/fixtures/tenants.yml
- test/system/fs/message_drafts_test.rb
Vyber boxu, do ktoreho sa nahra uploadnute podanie sme neobmedzovali na tenanta.😶
> User can upload a message draft only to the tenant's boxes

- app/models/filter_subscription.rb
- app/models/searchable/message_thread.rb
- app/models/searchable/message_thread_query.rb
- test/models/searchable/message_thread_query_test.rb
Pridana funkcionalita: 
- PREFIX search
- minimalne 4 znaky 
- na konci hviezdicka
- max. jedno taketo slovo viem vyhladavat (inak sa spravi exact match)
- funguje aj s labels, t.j. (mam zvolenu label + jednu expression, ktoru vyhladavam `zmluv*`)
> Allow prefix fulltext search using an asterisk

- app/jobs/fs/download_sent_message_related_messages_job.rb
- test/jobs/fs/download_sent_message_related_messages_job_test.rb
Sice sme spravili upravy v #517, job vyfailuje, ale retryuje sa. To nechceme, ved aj tak sync bezi kazde 2h, zbytocne tam tieto joby netocme dokola. Potrebujeme len, aby takyto job vyfailoval, nech vieme o tom, ze sa nieco deje.
> GO-164 Do not retry Fs::DownloadSentMessageRelatedMessagesJob if NoRelatedMessagesError

- app/components/settings/rules/actions_form_component.html.erb
- app/components/settings/rules/conditions_form_component.html.erb
- app/components/settings/rules/rule_form_component.html.erb
- app/views/admin/automation_webhooks/_form.html.erb
Isla som spisat tuto issue na GH, nech si moze niekto potiahnut, ale zistila som, ze rychlejsie to je rovno fixnut ako popisovat. Problem sa tykal admin modalov, kde su dve tlacidla vedla seba a jedno ma nastaveny border, druhe nie, tak to vizualne trochu bolo posunute.
> GO-26 Fix some admin buttons with added border

- app/models/automation/condition.rb
- test/fixtures/automation/actions.yml
- test/fixtures/automation/conditions.yml
- test/fixtures/automation/rules.yml
- test/fixtures/govbox/messages.yml
- test/fixtures/tags.yml
- test/models/automation/rule_test.rb
Ukazalo sa, ze niektore XML, ktore prichadzaju z UPVS maju escapovanu diakritiku, co sposobilo problem pri matchovani obsahu priloh v automation, napr. ked chceme ku kazdej uspesnej registracii certifikatu na UPVS pridat Tag, hlada match na "úspešne spracovaná", pricom XML vyzera takto:
<ns6:InformationMessage xmlns:ns6="http://schemas.gov.sk/form/G2G.InformationMessage/1.3">
<ns6:Subject>Spracovanie po&#x17E;iadavky v registri autentifika&#x10D;n&#xFD;ch certifik&#xE1;tov</ns6:Subject>
<ns6:Text>&#x17D;iados&#x165; o zmenu z&#xE1;pisu autentifika&#x10D;n&#xE9;ho certifik&#xE1;tu v registri autentifika&#x10D;n&#xFD;ch certifik&#xE1;tov bola &#xFA;spe&#x161;ne spracovan&#xE1; 29.11.2024 13:00.</ns6:Text>
</ns6:InformationMessage>
Upravila som tak, aby sa matchovanie kontrolovalo voci UTF-8 …
> GO-166 Update content_match? conditions in Automation

- public/openapi.yaml
Sync method was ignoring documented lastId parameter. It works fine with last_id
> Fix lastId parameter in openapi.yaml

- app/views/api/messages/search.json.jbuilder
- app/views/api/messages/show.json.jbuilder
- public/openapi.yaml
Is there any reason why the message `thread_id` is in the API `messages/sync` but not in `messages/{id}` and `messages/search`?
This PR consistently adds the `thread_id` to `messages/{id}` and `messages/search`. But it's possible I'm missing something and it's meant to be without it.
It's not fully tested yet, so it's a draft.
> Add thread_id to all message API endpoints

- app/controllers/api/messages_controller.rb
- app/jobs/govbox/submit_message_draft_job.rb
- app/models/message_object.rb
- db/migrate/20250114170638_add_description_to_message_objects.rb
- db/schema.rb
- public/openapi.yaml
Description atribut sme doteraz v GO nepouzivali, ale ukazalo sa, ze niekedy ho pri podaniach moze pouzivatel chciet vyplnit (podania cez API).
> Add description attribute to message objects

- app/components/settings/rules/automation_rules_table_row_component.html.erb
- app/components/settings/rules/condition_form_component.html.erb
- app/components/settings/rules/conditions_form_row_component.html.erb
- app/models/automation/action.rb
- app/models/automation/condition.rb
- app/views/settings/automation_actions/_edit_form_unassign_message_thread_tag_action.turbo_stream.erb
- config/locales/sk.yml
- test/fixtures/automation/actions.yml
- test/fixtures/automation/conditions.yml
- test/fixtures/automation/rules.yml
- test/fixtures/govbox/messages.yml
- test/fixtures/message_thread_merge_identifiers.yml
- test/fixtures/message_threads.yml
- test/fixtures/message_threads_tags.yml
- test/fixtures/messages.yml
- test/fixtures/tags.yml
- test/models/automation/attachment_test.rb
- test/models/automation/rule_test.rb
Rozsiruje #532 o testy a nove typy conditions.
> Add new automation condition types & tests for automation UnassignMessageThreadTagAction

- app/javascript/controllers/dropzone_controller.js
Aktualne je potrebne vybrat vsetky XML subory na jedno otvorenie file upload dialogu. Dalsim otvorenim dialogu sa subory prepisuju, co robi klientovi problem, nakolko subory ma roztriedene v roznych priecinkoch a potrebuje to tam postupne povyberat.
Tu je pripraveny update, aby sa subory neprepisovali, ale pridavali.
> Enable choosing FS input XML files multiple times

- app/controllers/admin/boxes/fs_boxes_controller.rb
- app/views/admin/boxes/index.html.erb
Maly fix. Tlacidlo pripojit novu schranku nema v adminovi vyznam, moze maximalne sposobit problemy.
Vytvaranie schranok chceme povolit iba na zaklade existujucich zastupovani ku ApiConnection, co sa deje automaticky. Takze nie je potreba ziadne FS schranky pridavat este bokom.
> Do not allow to add FS boxes manually

- app/models/fs/message.rb
- app/views/fs/messages/_delivery_report.html.erb
Ukazalo sa, ze vo vizualizacii FS potvrdeniek neuvadzame pre atribut 'Typ dokumentu' zhodnu hodnotu s FS portalom. Podla mna spatne spravy aktualizovat nie je potrebne (kto stahuje, riesi potvrdenky to uz ma stiahnute v povodnej podobe).
> GO-199 Update 'Typ dokumentu' value in FS DeliveryReport visualisation

- app/jobs/upvs/download_form_related_documents_job.rb
- app/models/upvs/form.rb
- db/migrate/20250205125502_add_downloadable_to_upvs_forms.rb
- db/schema.rb
Mame zopar UPVS formularov, ktore su specialnymi pripadmi (ORSR formulare), ktore nemaju bezne identifikatory ako zvysne UPVS formulare a nie su dostupne na ulozisku formularov.
Formulare sa ale v GO vyuzivaju a pravidelne stahovanie updateov k formularom nam failuje pri tychto specialitkach. Updaty k nim stahovat standardnym sposobom nechceme.
Chceme, aby nam to nefailovalo, zbytocne nas to "zaslepuje" pred realne problematickymi jobmi.
> GO-202 Mark some UPVS forms as not downloadable

- app/jobs/add_inbox_tag_to_thread_job.rb
- app/jobs/add_inbox_tag_to_threads_job.rb
- app/models/govbox/message.rb
- app/models/inbox_tag.rb
- app/models/tenant.rb
- db/migrate/20250204074342_create_inbox_tag.rb
- db/schema.rb
- test/fixtures/govbox/messages.yml
- test/fixtures/tags.yml
- test/models/automation/rule_test.rb
- test/models/govbox/message_test.rb
Co chceme dosiahnut:
- aby vlakno bolo oznacene za neprecitane iba ak pride plnohodnotna inboxova sprava
- aby vlakna, ktore obsahuju aspon jednu plnohodnotnu inboxovu spravu boli oznacene Inboxovym stitkom (ten je aktualne schovany, ale umoznuje vytvorit filter "Doručené", kt. sa správa podobne ako v gmaili).
Potrebujeme to preto, aby po odosielani podani sa nenasypalo do GO velke mnozstvo odoslanych sprav, ktore sa tvaria ako nove a treba ich otvorit a vyhodnotit (ci to je nieco na spracovanie).
> GO-181 Create InboxTag in order to filter only delivered significant messages

- app/models/fs/message.rb
- test/fixtures/messages.yml
- test/models/fs/message_test.rb
V #546 sme vyriesili oznacenie existujucich sprav (UPVS, aj FS) inboxovym tagom + oznacovanie novych UPVS sprav pri spracovani, na nove FS spravy sa pozadublo. Tak pridavam.
Logika je jednoducha, ked sa stiahne inboxova sprava, pridavame tag na vlakno.
> GO-181 Add Inbox Tag to thread when new FS inbox message is processed

- app/helpers/message_object_helper.rb
- app/models/concerns/message_export_operations.rb
Ukazal sa problem s pripadom, kedy v ramci jednej spravy mozu mat objekty (alebo vnorene objekty v asice) rovnake nazvy.
Konkretne nam klient nahlasil pripad, kedy v exporte chyba jeden subor, lebo objekty su taketo:
form.asice
- form.xml
priloha1.asice
- **dokument.pdf**
priloha2.asice
-  **dokument.pdf**
Dvakrat tam je dokument.pdf, takze v exporte sa tie subory prepisu. Nazvy suborov som uplne nechcela kazit nejakym IDckom objektu, tak som sa snazila dorobit _(1), (2)_,... oznacovanie v nazvoch suborov pri exporte, aby teda tieto dva vnorene objekty v exporte mali nazvy: 
- dokument.pdf, dokument (1).pdf
> GO-206 Make message export file names unique

- app/models/fs/api_connection.rb
- test/fixtures/boxes.yml
- test/models/fs/api_connection_test.rb
Myslím, že ten `message_drafts_import_enabled` chceme nastavovať autmoaticky iba raz - pri vytvorení boxu - ak by sme he chceli niekedy meniť, aby sa nám potom neprepisoval.
> GO-161 fix boxify json settings search

- app/lib/utils.rb
Pri pridavani schranok zo zoznamu UPVS opravneni na zastupovanie bol problem s tym, ze uuid je uppercase, tak uuid bolo vyhodnotene za nevalidne.
> Make UUID_PATERN case insensitive

- config/application.rb
Aby sme sa vyhli zmazaniu vsetkeho predtym, ako sa dokonci cely batch jobov, potrebujeme ich na nejaky cas uchovavat. Naschval som nastavila hodnotu na 1 den a nie na iba minuty/hodinu, lebo moze ist aj o vacsie, dlhsie trvajuce joby v ramci jedneho batchu, napr. import draftov z velkeho balika.
> GO-209 Preserve succeeded good jobs for 1 day

- app/jobs/fs/download_sent_message_related_messages_job.rb
- app/lib/fs/api.rb
- test/jobs/fs/download_sent_message_related_messages_job_test.rb
V zozname prijatých jednu správu nevidno, ak sa pošle delegate_id. Vidno je ale práve bez neho. Stiahnuť sa tá konkrétna správa dá aj s delegate_id v obo.
Historicky nastal jeden takýto prípad, odkedy používame delegate_id (čo je asi dva mesiace). Takýto fix asi stojí za to - vyčistí nám healthcheck.
> GO-231 try fetching messages without delegate if empty

- app/models/automation/condition.rb
- test/models/automation/rule_test.rb
Potrebujeme kvoli vyzadovaniu podpisov. Povodne sme mysleli, ze bude stacit condition na connection, ale nie je to tak, potrebujeme kontrolovat aj typ spravy, aby sa podpisy vyzadovali iba na draftoch, nie plnohodnotnych spravach.
> Add Automation::ValueCondition

- app/views/api/messages/search.json.jbuilder
- public/openapi.yaml
Ako sme na meetingu riesili tento endpoint som si v API specifikacii vsimla, ze search endpoint nevracia metadata (kt. sme nedavno pridavali do endpointu na ziskanie detailu spravy).
> Add metadata to search message response

- app/jobs/fs/submit_message_draft_result_job.rb
- app/models/message.rb
Pri FS jobe sme Problemove tag po odoslani nemazali vobec (t.j. podanie, kt. malo napr. iba logicke chyby je aj po odoslani stale oznacene Problemove tagom) a pri UPVS jobe sice mazanie mame, ale chybal v metode `reload`, aby to zafungovalo.
> Remove Problemove tag after submission

- app/jobs/fs/sync_all_boxes_job.rb
Zaroven ponechavame aj `perform_limit` v samotnom sync jobe, aby sme to vedeli limitovat aj tam, predislo "kopeniu".
> GO-249 Schedule FS sync job with wait statement

- app/views/api/messages/search.json.jbuilder
- app/views/api/messages/show.json.jbuilder
- app/views/api/messages/sync.json.jbuilder
- public/openapi.yaml
- test/integration/messages_api_test.rb
V https://github.com/slovensko-digital/govbox-pro/pull/619 sme pridali moznost ziskat PDF vizualizaciu objektu spravy. Zabudlo sa vsak na to, ze ID objektu v ziadnych responses nevraciame. Tak som ID pridala vsade, kde objekty vraciame a rovno som zjednotila som responsy k detailu spravy (kedze tam v poslednej dobe nieco pribudalo a nebolo to uplne jednotne na vsetkych 3 endpointoch, cez ktore sa da ziskat detail spravy).
> GO-261 Add message object ID to message show response

- app/models/concerns/pdf_visualization_operations.rb
Vo vseobecnosti, v core plati, ze chceme generovat PDF vizualizaciu XMLka z XSL-FO ak existuje. Ak nie, tak chceme PDF generovat z GO HTML vizualizacie.
FS potvrdenky su ale vynimkou. Tam XSL-FO existuje, lebo FS potvrdenky vyuzivaju rovnaky formular ako je v UPVS svete, ale nechceme ho matchnut na FS spravu. Nechceme to, lebo vizualizacia v FS svete je ina. 
Takze mam takyto skaredy fix, aby sa k FS spravam nematchoval UPVS formular.
> GO-137 Do not match UPVS form for FS EdDelivery reports

- app/models/export.rb
Prehodila som priority pomenovania. Mame teraz 3 urovne:
- pomenovanie podla typu formulara
- pomenovanie podla typu spravy
- default
Podla priority by to malo byt takto:
- pomenovanie podla typu spravy (aby bolo mozne pomenovat potvrdenku inak ako podanie - to je hlavna poziadavka)
- pomenovanie podla typu formulara (aby napr. SVDPH podania mohli byt pomenove SV alebo akokolvek inak podla zelania klienta)
- default
> GO-137 Update export files naming

- app/models/fs/box.rb
- test/models/fs/box_test.rb
Short name is supposed to be unique for a tenant. Name can be the same, if the uri is different.
closes #581
> Add uri to uniqueness scope of FS Box name

- app/models/export.rb
- app/views/message_threads/bulk/exports/edit.html.erb
Pri exporte pouzivatela castokrat zaujima datum danej spravy a su tu podla mna dva rozne pripady:
- Pri FS podaniach zaujima pouzivatela datum podania (datum odoslanej spravy),
- Pri UPVS spravach zaujima datum dorucenia konkretnej spravy. 
Preto navrhujem takuto upravu.
> GO-300 Add datum_dorucenia variable to exports
