slovensko-digital/govbox-pro

- Gemfile
- Gemfile.lock
- config/application.rb
@luciajanikova vieme skusit toto na staging ci to fixne problem?
> Try importmap downgrade

- app/components/message_template_recipients_component.html.erb
- app/views/message_templates/search_recipients_list.turbo_stream.erb
> GO-293 Update recipients list formatting & fix incorrect URL in recipients search

- app/controllers/message_drafts_controller.rb
- app/models/govbox/submit_message_draft_action.rb
- app/models/govbox/submit_message_drafts_action.rb
- app/policies/message_draft_policy.rb
- app/views/message_drafts/index.html.erb
- config/routes.rb
Vyhodila som moznost `submit_all` z tej schovanej stranky importovanych draftov, myslim si, ze uz mame na to lepsi mechanizmus.
`SubmitMessageDraftsAction` nebola spravne implementovana, neriesil sa tam problem naschedulovania x sync jobov, takze som upravila. Rovno som action pouzila aj v controlleri pre jednotlivy submit (nie hromadny).
> GO-60 Update bulk submit

- app/components/message_draft_body_component.html.erb
- app/components/message_draft_component.html.erb
- app/jobs/govbox/submit_message_draft_job.rb
- app/models/message_draft.rb
- app/models/submission_error_tag.rb
- app/models/tenant.rb
- db/migrate/20240322132501_create_submission_error_tag.rb
- db/schema.rb
> GO-51 Create Submission error tag

- app/models/govbox/message.rb
Ukazalo sa ako problem pri importe sprav v PROD. Pri notifikacii o doruceni je hodnota `message.metadata["delivery_notification"]["consignment"]["subject"]` prazdny string, takze failujeme na tom, ze povinny atribut `MessageThread.title` je prazdny.
> Fix setting MessageThread title

- app/controllers/admin/boxes_controller.rb
- app/policies/admin/box_policy.rb
- app/views/admin/boxes/index.html.erb
- app/views/admin/boxes/show.html.erb
- config/routes.rb
Zavedena zmena v Adminovi, aby nemohol len tak mazat schranky
> GO-54/Admin-box-delete

- app/jobs/govbox/submit_message_draft_job.rb
- app/models/message.rb
- app/models/message_draft.rb
- app/models/upvs/message_template.rb
- app/models/upvs/service_with_form_allow_rule.rb
- db/migrate/20240408100351_add_default_value_for_message_template_metadata.rb
- db/schema.rb
Zapracovanie pripomienok s predcasne uzatvoreneho PR: https://github.com/slovensko-digital/govbox-pro/pull/351
> GO-67 Small after review updates on MessageDrafts

- app/controllers/message_objects_controller.rb
- app/jobs/govbox/process_message_job.rb
- app/models/message.rb
Mali sme zadratovane, ze draft moze byt iba typu `MessageDraft`, co uz neplati.
> Updates after adding new message type

- app/components/signing/signers_requests/list_component.html.erb
- app/controllers/concerns/tag_creation.rb
- app/controllers/message_drafts/signature_requests_controller.rb
- app/controllers/message_threads/bulk/signings_controller.rb
- app/models/group_membership.rb
- app/models/message_object.rb
- app/models/message_thread.rb
- app/models/relation_changes.rb
- app/models/signer_group.rb
- app/models/tenant.rb
- app/models/user_group.rb
- db/migrate/20240613095110_create_signer_group_signing_tags.rb
- db/schema.rb
- test/fixtures/fs/forms.yml
- test/fixtures/group_memberships.yml
- test/fixtures/groups.yml
- test/fixtures/message_objects.yml
- test/fixtures/message_objects_tags.yml
- test/fixtures/message_threads.yml
- test/fixtures/message_threads_tags.yml
- test/fixtures/messages.yml
- test/fixtures/tag_groups.yml
- test/fixtures/tags.yml
- test/fixtures/users.yml
- test/models/message_object_test.rb
- test/system/message_threads_bulk_sign_test.rb
- test/system/message_threads_test.rb
Znovuotvoreny PR https://github.com/slovensko-digital/govbox-pro/pull/436, nepodarilo sa mergnut kvoli blikajucim testom, vid https://github.com/slovensko-digital/govbox-pro/pull/436#issuecomment-2175263038.
> GO-105 Bulk sign objects by any signer

- app/components/message_draft_body_component.html.erb
- app/jobs/fs/validate_message_draft_result_job.rb
- config/tailwind.config.js
> GO-111 Update saving FS message drafts validation errors

- .github/workflows/workflow.yml
Rovnako sme to menili aj na Autograme. Teraz sa púšťajú testy v PR 2x pre každý push, lebo to matchuje push aj PR naraz. S touto zmenou sa budú púšťať testy raz pre každý push v PR a raz po mergi do mainu.
> More efficient GH actions

- db/migrate/20240916130319_update_replyable_values_on_messages.rb
- db/schema.rb
> GO-106 Rollback migration

- config/initializers/omniauth.rb
Closes https://github.com/slovensko-digital/govbox-pro/issues/456
ako bolo písané v issue, ak nastane chyba tak vrátime uživateľa späť na main page
> fix: logout on callback error

- app/jobs/govbox/submit_message_draft_job.rb
> GO-139 Do not retry on Submission Error

- app/javascript/controllers/dropzone_controller.js
- app/views/fs/message_drafts/_new_form.html.erb
Pridany pocet, ktory sa zobrazi po nahrati prvych suborov.
> Add filecount to FS list

- app/models/fs/message.rb
Existujuce spravy navrhujem upravit cez konzolu, aby sme nemali problem s prilis dlhym bezanim migracie.
> GO-153 Collapse associated outbox message when inbox message received in thread

- app/components/message_threads_table_row_component.html.erb
> GO-175 Show date with time of last delivered message in threads list

- config/application.rb
> Cleanup preserved jobs after 2 days

- config/application.rb
By default sa joby mazu kazdych 10 minut/po 1000 joboch.
> GO-209 Do not preserve succeeded jobs

- app/jobs/upvs/drafts/load_content_job.rb
- app/models/validators/message_drafts_import_validator.rb
Rozsirenie o dalsie varianty pomenovania priecinkov v baliku.
> Accept podpisovat folders in upvs drafts import

- app/controllers/admin/api_connections/fs_api_connections_controller.rb
- app/views/admin/api_connections/fs_api_connections/_form.html.erb
- app/views/admin/api_connections/fs_api_connections/new.html.erb
- app/views/admin/api_connections/index.html.erb
Remove fields sub, api_token_private_key in FS connection edit form.
> Remove FS connection creation via UI

- app/controllers/admin/api_connections/fs_api_connections_controller.rb
- app/models/api_connection.rb
- app/models/fs/api_connection.rb
- app/models/govbox/api_connection.rb
- app/models/govbox/api_connection_with_obo_support.rb
- app/models/sk_api/api_connection_with_obo_support.rb
- app/views/admin/api_connections/fs_api_connections/_form.html.erb
- db/migrate/20250426132809_add_name_to_api_connections.rb
- db/migrate/20250426150801_add_name_to_api_connections.rb
- db/schema.rb
Make the name attribute editable
> Add name attribute to ApiConnection

- app/models/tenant.rb
Funkcionalita spojena s tymto tagom sa pridavala na hackdayi a akosi sa zabudlo na vytvaranie tohto tagu pre novych tenantov. Pri existujucich som uz dovyrabala tagy.
> Create tenant unprocessable tag after tenant created

- app/jobs/fs/download_sent_message_related_messages_job.rb
- app/jobs/fs/sync_box_job.rb
- app/models/fs/box.rb
- test/models/box_test.rb
Pretestovane, spravy sa neoznacuju za precitane.
> GO-249 Update FS sync logic

- app/controllers/message_threads/bulk/exports_controller.rb
- app/jobs/export_job.rb
- app/models/export.rb
- app/views/message_threads/bulk/exports/edit.html.erb
- db/migrate/20250721071231_create_good_job_execution_error_backtrace.rb
- db/migrate/20250721071232_create_good_job_process_lock_ids.rb
- db/migrate/20250721071233_create_good_job_process_lock_indexes.rb
- db/schema.rb
- test/jobs/govbox/submit_message_draft_job_test.rb
- test/lib/event_bus_test.rb
- test/models/message_thread_test.rb
> Better exports
